# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '4/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.base_ref != 'auto-commit' }}  # 替换为您的目标分支名
    run: exit 1

    steps:
      # 2. 条件验证：仅处理特定分支
      - name: Check target branch
        if: ${{ github.base_ref != 'auto-commit' }}  # 替换为您的目标分支名
        run: exit 1
            
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          #

      - name: Run Python Script
        run: |
          cd Python
          sh run.sh

      - name: Commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m"action:`date`"
          git pull --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
