# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: PythonWorkflow

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '1/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckoutAutoCommitBranch
        uses: actions/checkout@v4
        with:
          ref: auto-commit  # 强制检出auto-commit分支

      - name: SetUpPython3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: InstallDependencies
        run: |
          python -m pip install --upgrade pip
          # 检查并安装requirements.txt中的依赖
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # 确保requests库始终安装
          pip install requests

      - name: RunPythonScript
        run: |
          if [ -d "Python" ]; then
            cd Python && sh run.sh
          else
            echo "::error::Python目录未找到！"
            exit 1
          fi

      - name: CommitChanges
        id: commit
        run: |
          # 设置精确到毫秒的时间戳
          TIMESTAMP=$(date +'%Y%m%d%H%M%S%9N')
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add .
          # 检查是否有文件需要提交
          if git diff-index --quiet HEAD --; then
            echo "::set-output name=has_changes::false"
            echo "No changes to commit"
          else
            git commit -m "action:$TIMESTAMP"
            echo "::set-output name=has_changes::true"
          fi

      - name: PullLatestChanges
        if: steps.commit.outputs.has_changes == 'true'
        run: git pull --rebase origin auto-commit

      - name: PushChanges
        if: steps.commit.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-commit
